### PR TITLE
bench: add benchmark for vmemcache_get()

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/vmemcache/46)

### CODE REVIEW

**Comment by ldorau** [comment]
This PR contains PR https://github.com/pmem/vmemcache/pull/43

**Comment by ldorau** [comment]
@kilobyte please review

**Comment by kilobyte** [comment]
(Reviewed diff from #43 only.)

The arg parsing is pretty repetitititive, but deduplicating that code might be debatable.

**Comment by ldorau** [comment]
Rebased

**Comment by ldorau** [comment]
This PR contains PR https://github.com/pmem/vmemcache/pull/63

**Pull request merged**
