### PR TITLE
Fix build without pkg-config present.

### PR DESCRIPTION
**Pull request by kilobyte**
We tried to make this work but never actually tested.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/vmemcache/173)

### CODE REVIEW

**Comment by kilobyte** [comment]
Yeah: `apt purge pkg-test` then run cmake.

**Comment by ldorau** [comment]
> Yeah: `apt purge pkg-config` then run cmake.

I meant a unit test in out tree....

**Comment by marcinslusarz** [comment]
There is a warning now if pkg-config was not found (#205), so this PR should not be needed.

**Comment by marcinslusarz** [comment]
You are trying to deal with incorrect configuration, that can be easily fixed by installing pkg-config.
We can't just depend on pkg-config because Valgrind is optional.

We can revisit this when you find an OS with Valgrind, but without pkg-config.
There is nothing to fix on the vmemcache side.

**Comment by kilobyte** [comment]
In that case, it would need to be added to README.

But I don't get why — we already use a tool for finding dependencies (cmake), so optionally calling another one (pkg-config) seems pointless.

As for "an OS with Valgrind, but without pkg-config" — that's kind of like writing a script with #!/bin/zsh instead of sh or bash.  Sure, all common distros do have zsh in their repositories, but it's not ubiquitously installed, and, in our case, offers no extra functionality whatsoever.  Like that dependency on zsh, we can require the user to have pkgconfig, but it's wrong to have an undocumented requirement.

**Pull request closed without merging**
