### PR TITLE
fix statistic of gets

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/vmemcache/124)

### CODE REVIEW

**Comment by kilobyte** [comment]
I guess we're at a disagreement what a hit/miss means.  Let's review all cases:

### Before ###
||get|hit|miss|
|-|-|-|-|
|in cache|+1|+1|0|
|no callback|0|-1|+1|
|callback delivered|+1|0|+1|
|callback lied|0|-1|+1|

Not only gets don't get counted, the number of hits **decreases** (possibly going into unsigned negatives).

### After ###
||get|hit|miss|
|-|-|-|-|
|in cache|+1|+1|0|
|no callback|+1|0|+1|
|callback delivered|+2|+1|+1|
|callback lied|+2|0|+2|

Here, a get, and possibly as miss, are counted twice.

I'm pondering a change to the API that'd eliminate the possibility of callback lying (and guarantee the get to succeed), but that'd get rid of only the last row.  We still need to decide how to count successful callbacks...

**Comment by pbalcer** [comment]
`callback delivered 	+2 	+1 	+1`
is equivalent to:
cache_get() == NULL /* get + miss */
cache_put()
cache_get() == ENTRY /* get + hit */

`callback lied 	+2 	0 	+2`
is equivalent to:
cache_get() == NULL /* get + miss */
cache_put()
cache_get() == NULL /* get + miss */


Isn't this the thing we want to achieve? We won't have over 100% hit ratio or negative miss ratio.

**Comment by kilobyte** [comment]
I've overhauled the on_miss path (#137); it happens to fix the "no callback" case and makes it impossible for the callback to lie.  We still need to decide how to count successful callbacks.

**Comment by kilobyte** [comment]
Ie, after the refactoring in #137 the state is:

||get|hit|miss|
|-|-|-|-|
|in cache|+1|+1|0|
|no/failed callback|+1|0|+1|
|callback delivered|+1|0|+1|

Which we can keep or further change — that PR intends to modify code rather than stats.

**Comment by ldorau** [comment]
It is replaced by #137 and #138

**Pull request closed without merging**
