### PR TITLE
Fix enabling statistics in tests and benchmarks

### PR DESCRIPTION
**Pull request by ldorau**
The statistics are always disabled and cannot be enabled
in tests and benchmarks now.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/vmemcache/191)

### CODE REVIEW

**Comment by ldorau** [comment]
@kilobyte please test and review

**Comment by kilobyte** [comment]
Well...
`
vmemcache_test_heap_usage.c:244 in test_heap_usage(): Final heap usage is different than 0 (40): possible memory leak
`

And it reproduces only on one of three machines I tested on.

**Comment by kilobyte** [comment]
Turns out the failure reproduces only with gcc-9, with gcc-8 all is ok.

**Comment by kilobyte** [comment]
And the regression **does** happen on master, thus is not related to this pull request.  Not surprisingly, bisects to 76b520ceb65e390255b9126354af1dc536563d14 (ie, when this test got added).

**Comment by ldorau** [comment]
@marcinslusarz This the 2nd PR to be merged.

**Pull request merged**
