### PR TITLE
common: fix build on old gcc/clang

### PR DESCRIPTION
**Pull request by pbalcer**
This change is [Reviewable](https://reviewable.io/reviews/pmem/vmemcache/250)

### CODE REVIEW

**Comment by pbalcer** [comment]
we really ought to upgrade the CI (ubuntu 18.04 and fedora 28...) images...

**Comment by pbalcer** [comment]
It broke on ubuntu 18.04 we have on travis.

**Comment by kilobyte** [comment]
`rmadison -u ubuntu gcc` says even 12.04 defaulted to gcc-4.6, while 18.04 has gcc-7.4 (7.3 before updates).

**Comment by pbalcer** [comment]
Hm, you are right. Then this is weird:
https://travis-ci.org/github/pmem/vmemcache/jobs/737067565

And the fact that this patch helped is even weirded.

**Pull request merged**
