### PR TITLE
[NOT FOR MERGING] multi-file backend

### PR DESCRIPTION
**Pull request by kilobyte**
I want to compare our speed to just writing entries to a bunch of files.  On traditional disks, heavily optimized filesystem code may win despite drastically worse metadata costs, let's check that.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/vmemcache/184)

### CODE REVIEW

**Comment by kilobyte** [comment]
Results measured on spinning rust, bench_simul max_size=32M
* increasing block size to 4K doubles performance (as expected) — same would probably happen on any not byte-addressable backing; we should autodetect this
* writing values to separate files (as on this branch) doubles performance again

I suspect that even a fast NVME disk would suffer the same issues (too lazy to benchmark...), and fallocate(FALLOC_FL_ZERO_RANGE) or using pwrite() would be a fix.

Another interesting check would be to compare this branch on pmem — perhaps ext4's allocator might be better than ours?

**Comment by ldorau** [comment]
Can we close this PR as it is NOT FOR MERGING?

**Comment by kilobyte** [comment]
Yeah — a branch on my repo is not as easy to find, but it's not like this kind of testing is a priority for now.

**Comment by ldorau** [comment]
> Yeah — a branch on my repo is not as easy to find, but it's not like this kind of testing is a priority for now.

But a closed PR is easy to find, so just do not delete the branch ;-)

**Pull request closed without merging**
