### PR TITLE
bench: print hits and size of used pool in percents

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/vmemcache/136)

### CODE REVIEW

**Comment by marcinslusarz** [comment]
This PR depends on #124, right?

**Comment by kilobyte** [comment]
@marcinslusarz: not really — #124 merely fixes a bug, and, in my opinion, introduces another (but it's arguable based on what a "hit" means).  Printing stats doesn't depend on the data being valid or not.

**Comment by marcinslusarz** [comment]
Well, if hit > get because of bug (or misunderstanding of what hit and get means), then this patch may print hit ratios >100%. I think the underlying problem should be solved first...

**Comment by kilobyte** [comment]
Not any more wrong than printing 18446744073709551615 as we already do.

Imagine code that consists of:
```
    int four = 2 + 3;
    printf("ressult = %d\n", four);
```
Fixing the typo (ie, improving display) is unrelated to fixing bugs in actual calculation.

**Comment by marcinslusarz** [comment]
This is not the same - current benchmark doesn't print anything so it's correct. This PR introduces a regression by printing incorrect information.

**Comment by kilobyte** [comment]
Hmm right, you have a point.  Please merge #137 then, as a side effect that PR fixes statistics for one particular meaning of "hit" (where a miss satisfied by the callback doesn't count as a hit) — we can then discuss what we want in #124.

**Pull request merged**
