### PR TITLE
test: limit number of threads and ops in Helgrind test

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/vmemcache/54)

### CODE REVIEW

**Comment by ldorau** [comment]
@kilobyte please review

**Comment by kilobyte** [comment]
The usual gripe about arg parsing being a pile of nastily duplicated code applies, but I guess it's a task for the person who whines.

**Comment by ldorau** [comment]
This PR contains PR https://github.com/pmem/vmemcache/pull/63

**Comment by ldorau** [comment]
Rebased and all issues resolved.

**Comment by ldorau** [comment]
Setting test parameters moved

**Pull request merged**
