### PR TITLE
add abstraction layer for vmemcache indexing API

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/vmemcache/11)

### CODE REVIEW

**Comment by ldorau** [comment]
@kilobyte please review

**Comment by ldorau** [comment]
@marcinslusarz This is the most important PR in this repo now - to be merged as the 1st one.

**Comment by ldorau** [comment]
@kilobyte please review

**Comment by kilobyte** [comment]
Note that my remark is not a blocker — this API can be changed later.

**Comment by ldorau** [comment]
@marcinslusarz ping, anything left to be changed?

**Pull request merged**
