### PR TITLE
｢make install｣

### PR DESCRIPTION
**Pull request by kilobyte**
I'd like to be able to `#include <libvmemcache.h>` like the docs say...

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/vmemcache/147)

### CODE REVIEW

**Comment by marcinslusarz** [comment]
Please add a test that builds small program for installed vmemcache on Travis.

**Comment by kilobyte** [comment]
Waiting for #149 then — it's meant for this kind of tests.

I intended to use it for autopkgtest, which takes-or-builds a package, installs it then runs out-of-tree tests against the installed library, but you probably mean manual `make install`, right?

That can be done two ways:
 * unprivileged, in a random dir, with mucking with include/library paths
 * privileged, in `/usr/local`

Our travis job uses a whole docker container, with sudo access — thus either is doable.  I'd thus prefer /usr/local as that's more straightforward — which one would you pick?

**Comment by marcinslusarz** [comment]
I'm for unprivileged dir with PKG_CONFIG_PATH.

**Comment by marcinslusarz** [comment]
I'm merging this, but please submit another PR with the changes I asked.

**Pull request merged**
