### PR TITLE
WIP: Misses are gets, too.

### PR DESCRIPTION
**Pull request by kilobyte**
This change is [Reviewable](https://reviewable.io/reviews/pmem/vmemcache/108)

### CODE REVIEW

**Comment by kilobyte** [comment]
Actually, it's more complex that that — we'd need to decide **what** a "get", "hit" and "miss" mean.

What prompted me to this commit was seeing (unsigned) negatives from statistics; I wrote this change without thinking.  But, it turns out that my reasoning is valid only if callbacks are not involved.

With them, current code can credit both a hit (``get_count``) and a miss (``miss_count``): the logic is:
 * get, if it fails:
 * on_miss callback, quit if that returns 0
 * another get (without any locks — may return something another thread just inserted, or fail if what the callback inserted got immediately evicted)

Yet the old (current) code naively returns ``get_count - miss_count`` which is untrue at least in the default (no callbacks) case.

**Comment by pbalcer** [comment]
vmemcache_get:
```
inc(get)
if (miss) {
  inc(miss)
  cb();
  if (inserted)
    inc(get) //we did search twice...
    inc(hit)
    return ...;
} else {
  inc(hit)
}
```
Will this work?

**Comment by ldorau** [comment]
Please see https://github.com/pmem/vmemcache/pull/124/files

**Comment by kilobyte** [comment]
Superseded.

**Pull request closed without merging**
