### PR TITLE
docker: print info about the configuration being run

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/vmemcache/39)

### CODE REVIEW

**Comment by ldorau** [comment]
@kilobyte please review

**Comment by kilobyte** [comment]
This script's output uses plenty of coloured highlights, thus I wonder: what about making such a section header more visible?  Not necessarily using colour: an empty line and =============== would work too.  And these can be combined...

**Comment by ldorau** [comment]
> This script's output uses plenty of coloured highlights, thus I wonder: what about making such a section header more visible? Not necessarily using colour: an empty line and =============== would work too. And these can be combined...

Done

**Comment by ldorau** [comment]
@janekmi The Travis build is NOT in progress - it has PASSED - please see the link.

**Pull request merged**
