### PR TITLE
test: add Helgrind and Memcheck multi-threaded test

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/vmemcache/29)

### CODE REVIEW

**Comment by ldorau** [comment]
This PR contains PR https://github.com/pmem/vmemcache/pull/37

**Comment by ldorau** [comment]
This PR contains PRs: #37 and #41

**Comment by ldorau** [comment]
@kilobyte please review

**Comment by ldorau** [comment]
This PR contains PR #41

**Comment by janekmi** [comment]
Rebase please.

**Comment by ldorau** [comment]
Rebased

**Pull request merged**
